version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=f2RQ02VvgVpAYJP4ZGaZiW4SyjSKNPhmXhH7Tueo1HA=
      - BUNNY_CDN_STORAGE_URL=https://storage.bunnycdn.com
      - BUNNY_CDN_USERNAME=playable-factory
      - BUNNY_CDN_ACCESS_KEY=db38e5b4-17cf-4827-adb595d15b96-d67f-46f8
      - BUNNY_CDN_URL=https://playable-factory.b-cdn.net
    networks:
      - nextjs_network

networks:
  nextjs_network:
    driver: bridge
